server:
  port: ${DISCOVERY_PORT}

spring:
  main:
    banner-mode: off
  web:
    error:
      include-message: always
      include-stacktrace: never
  application:
    name: discovery-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:discovery-service/.env[.properties]

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION}
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  pattern:
    console: "%clr(%d{HH:mm}){magenta} %highlight(%-5level) %clr(%logger{30}){green} - %msg%n"
  level:
    root: INFO

    org.springframework: WARN
    org.hibernate: WARN
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    org.springframework.web: WARN

    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

    com.sphere: DEBUG